
package com.smi6.gestion_des_articles_informatique.view.connexion_home;

import com.smi6.gestion_des_articles_informatique.controller.autentification.Profile;

import com.smi6.gestion_des_articles_informatique.model.Utilisateur;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;

import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class ProfileView extends javax.swing.JFrame {
    
    private Utilisateur U;

 private Profile profileController; 
 
    /**
     * Creates new form ProfileView
     */

  
    public ProfileView(Utilisateur U){
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("my-persistence-unit");
        EntityManager em = emf.createEntityManager();
         this.profileController = new Profile(em);
            this.U = U;
       initComponents();
       this.setLocationRelativeTo(null);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButtonChangerMdp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldConfirmMdp = new javax.swing.JPasswordField();
        jPasswordFieldNouveauMdp = new javax.swing.JPasswordField();
        jPasswordFieldAncienMdp = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabellogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonChangerMdp1 = new javax.swing.JButton();
        jPasswordFieldAncienMdp1 = new javax.swing.JPasswordField();
        jPasswordFieldNouveauMdp1 = new javax.swing.JPasswordField();
        jPasswordFieldConfirmMdp1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 600));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 53, 36));
        jLabel2.setText("Profile");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Nom_Complet");

        jButtonChangerMdp.setBackground(new java.awt.Color(18, 53, 36));
        jButtonChangerMdp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonChangerMdp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChangerMdp.setText("Changer");
        jButtonChangerMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Entrer le nouvelle mots de passe");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Entrer l'ancien mots de passe");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Confirmation du nouveau mot de passe ");

        jPasswordFieldConfirmMdp.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldConfirmMdp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldConfirmMdp.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldConfirmMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmMdpActionPerformed(evt);
            }
        });

        jPasswordFieldNouveauMdp.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldNouveauMdp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldNouveauMdp.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordFieldAncienMdp.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldAncienMdp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldAncienMdp.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldAncienMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldAncienMdpActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Login");

        jLabelNom.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(18, 53, 36));
        jLabelNom.setText(this.U.getNomComplet());

        jLabellogin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabellogin.setForeground(new java.awt.Color(18, 53, 36));
        jLabellogin.setText(this.U.getLogin());

        jLabel3.setBackground(new java.awt.Color(18, 53, 36));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("changer le mot de passe");

        jButtonChangerMdp1.setBackground(new java.awt.Color(18, 53, 36));
        jButtonChangerMdp1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonChangerMdp1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChangerMdp1.setText("Retourner");
        jButtonChangerMdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangerMdp1ActionPerformed(evt);
            }
        });

        jPasswordFieldAncienMdp1.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldAncienMdp1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldAncienMdp1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldAncienMdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldAncienMdp1ActionPerformed(evt);
            }
        });

        jPasswordFieldNouveauMdp1.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldNouveauMdp1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldNouveauMdp1.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordFieldConfirmMdp1.setBackground(new java.awt.Color(239, 227, 194));
        jPasswordFieldConfirmMdp1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordFieldConfirmMdp1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordFieldConfirmMdp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmMdp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonChangerMdp1)
                        .addGap(723, 723, 723)
                        .addComponent(jButtonChangerMdp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldConfirmMdp)
                            .addComponent(jPasswordFieldNouveauMdp)
                            .addComponent(jPasswordFieldAncienMdp)
                            .addComponent(jLabellogin, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldAncienMdp1)
                            .addComponent(jPasswordFieldNouveauMdp1)
                            .addComponent(jPasswordFieldConfirmMdp1))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabellogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldAncienMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldNouveauMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordFieldConfirmMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPasswordFieldAncienMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPasswordFieldNouveauMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPasswordFieldConfirmMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChangerMdp)
                    .addComponent(jButtonChangerMdp1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangerMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdpActionPerformed
          try {
       String ancien = new String(jPasswordFieldAncienMdp.getPassword());
      String nouveau = new String(jPasswordFieldNouveauMdp.getPassword());
      String confirm = new String(jPasswordFieldConfirmMdp.getPassword());

 profileController.changerMotDePasse(this.U.getId(), ancien, nouveau, confirm);

       JOptionPane.showMessageDialog(this, "Mot de passe modifié avec succès !");
   } catch (Exception e) {
       JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
   }
    }//GEN-LAST:event_jButtonChangerMdpActionPerformed

    private void jPasswordFieldAncienMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldAncienMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldAncienMdpActionPerformed

    private void jPasswordFieldConfirmMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmMdpActionPerformed

    private void jButtonChangerMdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangerMdp1ActionPerformed
        // TODO add your handling code here:
                       Utilisateur user = this.U;
            if (user != null) {
        if (user.getRole() == Utilisateur.Role.admin) {
            Accueille_admin2 adminView = new Accueille_admin2(user); // Pass the user if needed
            adminView.setVisible(true);
        } else if (user.getRole() == Utilisateur.Role.utilisateur) {
            Accueille_avec_compte2 userView = new Accueille_avec_compte2(user);
            userView.setVisible(true);
        } else {
            Accueille_sans_compte2 A = new Accueille_sans_compte2();
            A.setVisible(true);
        }
    } else {
            Accueille_sans_compte2 A = new Accueille_sans_compte2();
            A.setVisible(true);
    }

    // Dispose the current window
    this.dispose();
    }//GEN-LAST:event_jButtonChangerMdp1ActionPerformed

    private void jPasswordFieldAncienMdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldAncienMdp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldAncienMdp1ActionPerformed

    private void jPasswordFieldConfirmMdp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmMdp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmMdp1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new ProfileView(null).setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChangerMdp;
    private javax.swing.JButton jButtonChangerMdp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabellogin;
    private javax.swing.JPasswordField jPasswordFieldAncienMdp;
    private javax.swing.JPasswordField jPasswordFieldAncienMdp1;
    private javax.swing.JPasswordField jPasswordFieldConfirmMdp;
    private javax.swing.JPasswordField jPasswordFieldConfirmMdp1;
    private javax.swing.JPasswordField jPasswordFieldNouveauMdp;
    private javax.swing.JPasswordField jPasswordFieldNouveauMdp1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
