/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.smi6.gestion_des_articles_informatique.view;
import com.smi6.gestion_des_articles_informatique.controller.*;
import com.smi6.gestion_des_articles_informatique.model.Utilisateur;
import java.io.File;
import javax.swing.JFileChooser; 
import javax.swing.filechooser.FileNameExtensionFilter;




/**
 *
 * @author YN
 */
public class Upload4 extends javax.swing.JFrame {
private File selectedPdfFile;
private Utilisateur U;

    /**
     * Creates new form Upload4
     */
    public Upload4(Utilisateur U) {
        initComponents();
        this.U = U;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_upload = new javax.swing.JLabel();
        L_titre = new javax.swing.JLabel();
        L_resume = new javax.swing.JLabel();
        L_auteurs = new javax.swing.JLabel();
        L_journaux = new javax.swing.JLabel();
        L_publierle = new javax.swing.JLabel();
        B_pdf = new javax.swing.JButton();
        TF_titre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_resume = new javax.swing.JTextArea();
        TF_auteurs = new javax.swing.JTextField();
        TF_journaux = new javax.swing.JTextField();
        TF_date = new javax.swing.JTextField();
        B_retourner = new javax.swing.JButton();
        B_enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 600));

        L_upload.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_upload.setForeground(new java.awt.Color(18, 53, 36));
        L_upload.setText("Upload");

        L_titre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_titre.setForeground(new java.awt.Color(18, 53, 36));
        L_titre.setText("Titre");

        L_resume.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_resume.setForeground(new java.awt.Color(18, 53, 36));
        L_resume.setText("Resume");

        L_auteurs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_auteurs.setForeground(new java.awt.Color(18, 53, 36));
        L_auteurs.setText("Auteurs");

        L_journaux.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_journaux.setForeground(new java.awt.Color(18, 53, 36));
        L_journaux.setText("Journaux");

        L_publierle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        L_publierle.setForeground(new java.awt.Color(18, 53, 36));
        L_publierle.setText("Publier le");

        B_pdf.setBackground(new java.awt.Color(18, 53, 36));
        B_pdf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        B_pdf.setForeground(new java.awt.Color(239, 227, 194));
        B_pdf.setText("PDF");
        B_pdf.setFocusable(false);
        B_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pdfActionPerformed(evt);
            }
        });

        TF_titre.setBackground(new java.awt.Color(239, 227, 194));
        TF_titre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TF_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_titreActionPerformed(evt);
            }
        });

        TA_resume.setBackground(new java.awt.Color(239, 227, 194));
        TA_resume.setColumns(20);
        TA_resume.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TA_resume.setRows(5);
        jScrollPane1.setViewportView(TA_resume);

        TF_auteurs.setBackground(new java.awt.Color(239, 227, 194));
        TF_auteurs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        TF_journaux.setBackground(new java.awt.Color(239, 227, 194));
        TF_journaux.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        TF_date.setBackground(new java.awt.Color(239, 227, 194));
        TF_date.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TF_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_dateActionPerformed(evt);
            }
        });

        B_retourner.setBackground(new java.awt.Color(18, 53, 36));
        B_retourner.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        B_retourner.setForeground(new java.awt.Color(239, 227, 194));
        B_retourner.setText("Retourner");
        B_retourner.setFocusable(false);
        B_retourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_retournerActionPerformed(evt);
            }
        });

        B_enregistrer.setBackground(new java.awt.Color(18, 53, 36));
        B_enregistrer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        B_enregistrer.setForeground(new java.awt.Color(239, 227, 194));
        B_enregistrer.setText("Enregistrer");
        B_enregistrer.setFocusable(false);
        B_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_enregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(L_publierle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_journaux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_auteurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_resume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_titre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L_upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_date, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(B_enregistrer)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(B_pdf)
                                    .addComponent(TF_auteurs, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                                    .addComponent(TF_journaux)
                                    .addComponent(jScrollPane1)))
                            .addComponent(TF_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(B_retourner))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_upload)
                    .addComponent(B_pdf))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_titre)
                    .addComponent(TF_titre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_resume)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_auteurs)
                    .addComponent(TF_auteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_journaux)
                    .addComponent(TF_journaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_publierle)
                    .addComponent(TF_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_retourner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_dateActionPerformed

    private void TF_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_titreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_titreActionPerformed

    private void B_retournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_retournerActionPerformed
            // TODO add your handling code here:
            // TODO add your handling code here:
        Utilisateur user = this.U;
            if (user != null) {
        if (user.getRole() == Utilisateur.Role.admin) {
            Accueille_admin2 adminView = new Accueille_admin2(user); // Pass the user if needed
            adminView.setVisible(true);
        } else if (user.getRole() == Utilisateur.Role.utilisateur) {
            Accueille_avec_compte2 userView = new Accueille_avec_compte2(user);
            userView.setVisible(true);
        } else {
            Accueille_sans_compte2 A = new Accueille_sans_compte2();
            A.setVisible(true);
        }
    } else {
            Accueille_sans_compte2 A = new Accueille_sans_compte2();
            A.setVisible(true);
    }

    // Dispose the current window
    this.dispose();        
        
    }//GEN-LAST:event_B_retournerActionPerformed

    private void B_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_enregistrerActionPerformed
    String titre = TF_titre.getText();
    String resume = TA_resume.getText();
    String auteurs = TF_auteurs.getText();
    String journaux = TF_journaux.getText();
    String datePublication = TF_date.getText();
    String quartile = "t";
    
    UploadController uploadController = new UploadController();
    
    Long userId = this.U.getId();
    
    try {
        uploadController.uploadArticle(userId, titre, resume, auteurs, journaux, datePublication, selectedPdfFile, quartile);
        
        // ✅ If everything OK, show success popup
        javax.swing.JOptionPane.showMessageDialog(this,
                "Article enregistré avec succès!",
                "Succès",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception ex) {
        // ❌ If an error, show error popup
        javax.swing.JOptionPane.showMessageDialog(this,
                "Erreur lors de l'enregistrement:\n" + ex.getMessage(),
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_B_enregistrerActionPerformed

    private void B_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pdfActionPerformed
        // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Choisir un fichier PDF");

    // Only allow PDF files
    FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichiers PDF", "pdf");
    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        selectedPdfFile = fileChooser.getSelectedFile();
        System.out.println("✅ Fichier PDF sélectionné : " + selectedPdfFile.getAbsolutePath());

        // Update button text to show selected filename (optional)
        B_pdf.setText(selectedPdfFile.getName());
    } else {
        System.out.println("❌ Aucun fichier sélectionné");
    }
        
    }//GEN-LAST:event_B_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Upload4(5L).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_enregistrer;
    private javax.swing.JButton B_pdf;
    private javax.swing.JButton B_retourner;
    private javax.swing.JLabel L_auteurs;
    private javax.swing.JLabel L_journaux;
    private javax.swing.JLabel L_publierle;
    private javax.swing.JLabel L_resume;
    private javax.swing.JLabel L_titre;
    private javax.swing.JLabel L_upload;
    private javax.swing.JTextArea TA_resume;
    private javax.swing.JTextField TF_auteurs;
    private javax.swing.JTextField TF_date;
    private javax.swing.JTextField TF_journaux;
    private javax.swing.JTextField TF_titre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
